# vim:set ft=tmux:
## name: Oasis Tokyo Night Moon
## author: custom

# Main
set -ogq @thm_strong_primary "#3d59a1"
set -ogq @thm_primary "#82aaff"
set -ogq @thm_light_primary "#b4f9f8"
set -ogq @thm_secondary "#ff9e64"
set -ogq @thm_prefix "#ff757f"
set -ogq @thm_fg "#c8d3f5"

# Surfaces and overlays
set -ogq @thm_core "#222436"
set -ogq @thm_mantle "#1e2030"
set -ogq @thm_surface "#2d3149"
set -ogq @thm_visual "#3b4261"

# General
set -ogq @thm_red "#ff757f"
set -ogq @thm_orange "#ff9e64"
set -ogq @thm_yellow "#ffc777"
set -ogq @thm_green "#c3e88d"
set -ogq @thm_teal "#86e2d5"
set -ogq @thm_blue "#82aaff"
set -ogq @thm_indigo "#c099ff"
